language: generic

os:
  - linux

before_install:
  # Compile Regent
  - if [ -d $HOME/legion ]; then git -C $HOME/legion pull; else git clone -b master https://github.com/StanfordLegion/legion.git $HOME/legion; fi
  - $HOME/legion/language/install.py --rdir auto
  - sudo ln -s $HOME/legion/language/regent.py /usr/local/bin/regent
  # Generate precomputed Boys values
  - python scripts/generate_boys_region.py src/mcmurchie/precomputedBoys.h

script:
  - python scripts/test.py

dist: trusty

addon:
  apt:
    update: true
    packages:
      clang-3.5
      libclang-3.5-dev
      llvm-3.5-dev
      python-numpy
      python-scipy


cache:
  directories:
    $HOME/legion
