language: generic

dist: trusty

os:
  - linux

before_install:
  - sudo apt-get update
  - sudo apt-get install -y clang-3.5 libclang-3.5-dev llvm-3.5-dev python-numpy python-scipy
  # Compile Regent
  - git clone -b master https://github.com/StanfordLegion/legion.git $HOME/legion
  - $HOME/legion/language/install.py --rdir auto --no-terra-cmake --terra-url https://github.com/StanfordLegion/terra.git --terra-branch luajit2.1
  - sudo ln -s $HOME/legion/language/regent.py /usr/local/bin/regent

script:
  - python3 scripts/test_boys.py
  - python3 scripts/test.py
  - cd src/cpp; LEGION="$HOME/legion" MAX_MOMENTUM=S make libjfock_tasks.so
  - cd src/cpp; LEGION="$HOME/legion" MAX_MOMENTUM=S make clean
  - cd src/cpp; LEGION="$HOME/legion" MAX_MOMENTUM=P make libjfock_tasks.so
  - cd src/cpp; LEGION="$HOME/legion" MAX_MOMENTUM=P make clean
  - cd src/cpp; LEGION="$HOME/legion" MAX_MOMENTUM=D make libjfock_tasks.so
  - cd src/cpp; LEGION="$HOME/legion" MAX_MOMENTUM=D make clean
