language: generic

dist: trusty

addons:
  apt:
    packages:
      - clang-3.5
      - libclang-3.5-dev
      - llvm-3.5-dev
      - python3-numpy
      - python3-scipy

os:
  - linux

before_install:
  - git clone -b master https://github.com/StanfordLegion/legion.git $HOME/legion
  - $HOME/legion/language/install.py --cmake --rdir auto --no-terra-cmake --terra-url https://github.com/StanfordLegion/terra.git --terra-branch luajit2.1
  - sudo make -C $HOME/legion/language/build install
  - sudo ln -s $HOME/legion/language/regent.py /usr/local/bin/regent

install:
  - # Compile libERIRegent.so
  - RG_MAX_MOMENTUM=D make
  - pushd .
  - # Compile test binary
  - cd src/tests/cpp; make
  - popd

script:
  - python3 scripts/test_boys.py
  - python3 scripts/test.py
