language: generic

dist: trusty

addons:
  apt:
    packages:
      - clang-3.5
      - libclang-3.5-dev
      - llvm-3.5-dev
      - python3-numpy
      - python3-scipy

os:
  - linux

before_install:
  # Compile Regent
  - git clone -b master https://github.com/StanfordLegion/legion.git $HOME/legion
  # TODO: https://github.com/StanfordLegion/legion/issues/667
  - pushd .; cd $HOME/legion; git checkout 0bd0b591ea33a335f0ea169a14125d9bd85e0ad7; popd;
  - $HOME/legion/language/install.py --rdir auto --no-terra-cmake --terra-url https://github.com/StanfordLegion/terra.git --terra-branch luajit2.1
  - sudo ln -s $HOME/legion/language/regent.py /usr/local/bin/regent

script:
  - python3 scripts/test_boys.py
  - python3 scripts/test.py
  - cd src/cpp
  - LEGION="$HOME/legion" MAX_MOMENTUM=S make libjfock_tasks.so
  - LEGION="$HOME/legion" MAX_MOMENTUM=S make clean
  - LEGION="$HOME/legion" MAX_MOMENTUM=P make libjfock_tasks.so
  - LEGION="$HOME/legion" MAX_MOMENTUM=P make clean
  - LEGION="$HOME/legion" MAX_MOMENTUM=D make libjfock_tasks.so
  - LEGION="$HOME/legion" MAX_MOMENTUM=D make clean
