language: generic

dist: trusty

addons:
  apt:
    packages:
      - clang-3.5
      - libclang-3.5-dev
      - llvm-3.5-dev
      - python3-numpy
      - python3-scipy

os:
  - linux

before_install:
  - git clone -b master https://github.com/StanfordLegion/legion.git $HOME/legion
  - $HOME/legion/language/install.py --cmake --rdir auto --no-terra-cmake --terra-url https://github.com/StanfordLegion/terra.git --terra-branch luajit2.1
  - sudo make -C $HOME/legion/language/build install
  - sudo ln -s $HOME/legion/language/regent.py /usr/local/bin/regent

install:
  - # Compile libERIRegent.so
  - RG_MAX_MOMENTUM=D make
  - pushd .
  - # Compile test binary
  - cd src/tests/cpp; make
  - popd

script:
  - python3 scripts/test_boys.py
  - LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib" python3 scripts/test.py
  - # TODO: Move these tests to the test script.
  - # Test kfock.
  - cd src
  - regent top_kfock.rg -L S -i tests/integ/h2 -v tests/integ/h2/kfock_output.dat
  - regent top_kfock.rg -L P -i tests/integ/h2o -v tests/integ/h2o/kfock_output.dat 
  - regent top_kfock.rg -L P -i tests/integ/co2 -v tests/integ/co2/kfock_output.dat
